---
groupsUrl:
  - file:///etc/calamares/modules/netinstall.yaml

required: false

label:
  sidebar: "Null Packages"
  title: "NullLinux Package Selection"
  subtitle: "Select the required packages during installation"
