---
modules-search:
  - /usr/lib/calamares/modules
  - /etc/calamares/modules

branding: null

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - netinstall
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - displaymanager
      - networkcfg
      - hwclock
      - packages
      - netinstall
      - umount
